events { worker_connections 1024; }

http {
    # 캐시 저장소 정의
    # 경로 : /var/cache/nginx
    # 저장소 이름 : ossdev_nginx_cache
    # 메모리 크기 : 10MB
    # 60분간 미사용 시 정리
    proxy_cache_path /var/cache/nginx levels=1:2 keys_zone=ossdev_nginx_cache:10m max_size=1g inactive=60m use_temp_path=off;
    server {
        listen 80;
        server_name localhost;

        location / {
            # 클라이언트 요청을 백엔드로 전달
            proxy_pass http://backend;

            # 캐싱 활성화
            proxy_cache ossdev_nginx_cache;
            proxy_cache_valid 200 20s; # 응답 성공(200)을 20초간 저장

            # 헤더에 정보 기록
            add_header X-Client-IP $remote_addr; # 클라이언트 실제 IP
            add_header X-Actual-Backend-IP $upstream_addr; # NGINX가 접속한 백엔드 IP
            add_header X-NGINX-Message "ossdev - NGINX confirmed request and forwarded to ossdev-backend-server"; # NGINX 통과 메시지
            add_header X-Cache-Status $upstream_cache_status; # 캐시 상태를 헤더에 표시
        }
    }
}
